# Copyright 2022 Mitchell Kember. Subject to the MIT License.
# Advent of Code 2022
# Day 5: Supply Stacks

Input ← use "Input" &i "common.ua"
Z ← use "Z" &i "common.ua"

# Initial state (list of top-down crate strings) and steps (table of n_src_dst).
# x ← {⊃(≡(□▽≠@ .)▽=1◿4⇡⧻.⍉⊜∘≠@\n.↙)(↯¯1_3⊜Z×⊃'≥@0'≤@9.↘⊗@m.↘)-1⊗@1. Input "2022_05"}

# ⊃↙↘-1⊗@1. Input "2022_05"
# ≡(□▽≠@ .)▽=1◿4⇡⧻.⍉⊜∘≠@\n.
# Init ←
# ↯¯1_3⊜Z×⊃'≥@0'≤@9.↘⊗@m.
# Steps ←

# Executes step 𝕨 on state 𝕩, applying 𝔽 on moved crates.

# Simulates all steps, applying 𝕏 on moved crates.

# Part 1
# S(⇌)

# Part 2
# S(∘)
