# Copyright 2023 Mitchell Kember. Subject to the MIT License.
# Advent of Code 2022
# Day 9: Rope Bridge

&fras "../../input/2022_09.in"

⊜(×⊏:1_¯1_0⊗:"RL"_"UD"⊃⊢(⋕↘2))≠@\n.

# Updates tail tx_ty to follow head hx_hy.
# F ← +⊃∘(×/↥≥2⊃⌵±-)

# Moves the head of the rope and updates all tail knots.
# M ← \F

# Knot positions during the simulation, with shape N_10.

# Part 1
# &p ⧻⊝≡'⊏1

# Part 2
# &p ⧻⊝≡'⊏¯1
